{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: oracle-credentials
  labels:
    {{- include "access-cdc.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.storeRef.name }}
    kind: {{ .Values.externalSecret.storeRef.kind }}
  target:
    name: oracle-credentials
    creationPolicy: Owner
  data:
    - secretKey: ORACLE_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecret.remoteKey }}
        property: ORACLE_PASSWORD
    - secretKey: APP_USER_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecret.remoteKey }}
        property: APP_USER_PASSWORD
    - secretKey: password
      remoteRef:
        key: {{ .Values.externalSecret.remoteKey }}
        property: APP_USER_PASSWORD
    {{- range .Values.oracle.schemas }}
    - secretKey: {{ . }}_PASSWORD
      remoteRef:
        key: {{ $.Values.externalSecret.remoteKey }}
        property: {{ . }}_PASSWORD
    {{- end }}
{{- end }}
