-- This script is used to truncate tables in the simulation environment for testing purposes.
TRUNCATE TABLE ABFCUBSLIVE.ACZB_DAILY_LOG;
TRUNCATE TABLE ABFCUBSLIVE.ACZB_HISTORY;

TRUNCATE TABLE WEBSERVE.PAYMENT_ROUTER_TXN_LOG;
TRUNCATE TABLE NIPSYSTEM.NIPX_DIRECT_CREDITS;
TRUNCATE TABLE NIPSYSTEM.NIPX_INBOUND_CREDITS;


truncate table ora_enriched_transactions;