--------------------------------------------------------------------------------------
-- Step 1: Enable ARCHIVELOG and FORCE LOGGING in Oracle Database

-- Connect to the database as a privileged user (e.g., SYSDBA)
sqlplus / as sysdba

-- Check current log mode
ARCHIVE LOG LIST

-- If not already enabled:
-- Put the database in mount mode
SHUTDOWN IMMEDIATE;
STARTUP MOUNT;

-- Enable archive log
ALTER DATABASE ARCHIVELOG;

-- Enable force logging
ALTER DATABASE FORCE LOGGING;

-- Open database
ALTER DATABASE OPEN;

-- Verify status
ARCHIVE LOG LIST

--------------------------------------------------------------------------------------------------
-- Step 2: Verify that the database is in ARCHIVELOG mode and FORCE LOGGING is enabled
SELECT LOG_MODE FROM V$DATABASE;
SELECT FORCE_LOGGING FROM V$DATABASE;



---------------------------------------------------------------------------------------
-- Step 3: Enable Database-Level Supplemental Logging
-- Enable minimal supplemental logging
ALTER DATABASE ADD SUPPLEMENTAL LOG DATA;
-- Enable supplemental logging for primary key columns
ALTER DATABASE ADD SUPPLEMENTAL LOG DATA (PRIMARY KEY) COLUMNS;
-- Enable supplemental logging for unique indexes
ALTER DATABASE ADD SUPPLEMENTAL LOG DATA (UNIQUE) COLUMNS;
-- Enable supplemental logging for foreign key columns
ALTER DATABASE ADD SUPPLEMENTAL LOG DATA (FOREIGN KEY) COLUMNS;
-- Enable supplemental logging for all columns
ALTER DATABASE ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;

-- Confirm
SELECT SUPPLEMENTAL_LOG_DATA_MIN FROM V$DATABASE;
-- Should say 'YES'


---------------------------------------------------------------------------------------
-- Step 4: Enable Table-Level Supplemental Logging for Each Table
ALTER TABLE ABFCUBSLIVE.ACZB_HISTORY           ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
ALTER TABLE ABFCUBSLIVE.ACZB_DAILY_LOG         ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
ALTER TABLE ABFCUBSLIVE.STZM_CUST_ACCOUNT      ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
ALTER TABLE ABFCUBSLIVE.STZM_CUSTOMER          ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
ALTER TABLE ABFCUBSLIVE.STZM_TRN_CODE          ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
ALTER TABLE NIPSYSTEM.NIPX_BANKS               ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
ALTER TABLE NIPSYSTEM.NIPX_DIRECT_CREDITS      ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
ALTER TABLE NIPSYSTEM.NIPX_INBOUND_CREDITS     ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
ALTER TABLE WEBSERVE.CSTM_PRODUCT_INTERFACE_MAPPING ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
ALTER TABLE WEBSERVE.PAYMENT_ROUTER_TXN_LOG    ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;


---------------------------------------------------------------------------------
-- Step 5:  Create the Debezium User (C##DEBEZIUM)
-- As SYSDBA
ALTER SESSION SET CONTAINER = CDB$ROOT;
CREATE USER C##DEBEZIUM IDENTIFIED BY oracle CONTAINER=ALL;

-----------------------------------------------------------------------------------
-- Step 6: Grant Required Privileges to Debezium User
ALTER SESSION SET CONTAINER = CDB$ROOT;
ALTER USER C##DEBEZIUM QUOTA UNLIMITED ON USERS;
GRANT CONNECT TO C##DEBEZIUM CONTAINER=ALL;
GRANT SELECT ANY TABLE TO C##DEBEZIUM CONTAINER=ALL;
GRANT CREATE TABLE TO C##DEBEZIUM CONTAINER=ALL;
GRANT SELECT ANY TRANSACTION TO C##DEBEZIUM CONTAINER=ALL;
GRANT SELECT ANY DICTIONARY TO C##DEBEZIUM CONTAINER=ALL;
GRANT LOGMINING TO C##DEBEZIUM CONTAINER=ALL;      -- Oracle 19c+
GRANT EXECUTE_CATALOG_ROLE TO C##DEBEZIUM CONTAINER=ALL;
GRANT FLASHBACK ANY TABLE TO C##DEBEZIUM CONTAINER=ALL;

-- For APEX/DBMS_LOB logging support (if needed by Debezium)
GRANT EXECUTE ON DBMS_LOGMNR TO C##DEBEZIUM CONTAINER=ALL;
GRANT EXECUTE ON DBMS_LOGMNR_D TO C##DEBEZIUM CONTAINER=ALL;
GRANT SELECT ON V_$DATABASE TO C##DEBEZIUM CONTAINER=ALL;
GRANT SELECT_CATALOG_ROLE TO C##DEBEZIUM CONTAINER=ALL;
GRANT SELECT ON V_$LOG TO C##DEBEZIUM CONTAINER=ALL;
GRANT SELECT ON V_$ARCHIVED_LOG TO C##DEBEZIUM CONTAINER=ALL;
GRANT SELECT ON V_$LOGMNR_CONTENTS TO C##DEBEZIUM CONTAINER=ALL;
GRANT SELECT ON V_$LOGMNR_LOGS TO C##DEBEZIUM CONTAINER=ALL;
GRANT SELECT ON V_$LOGMNR_PARAMETERS TO C##DEBEZIUM CONTAINER=ALL;
GRANT SELECT ANY DICTIONARY TO C##DEBEZIUM CONTAINER=ALL;
GRANT SELECT ON V_$TRANSACTION TO C##DEBEZIUM CONTAINER=ALL;
GRANT SELECT ON V_$CONTAINERS TO C##DEBEZIUM CONTAINER=ALL;



-----------------------------------------------------------------------------------
-- Step 6b: Grant Privileges in PDB (Required if CONTAINER=ALL grants don't propagate)
-- Connect to the PDB directly
ALTER SESSION SET CONTAINER = ACCESSBANK;
GRANT CREATE TABLE TO C##DEBEZIUM;
GRANT UNLIMITED TABLESPACE TO C##DEBEZIUM;
GRANT FLASHBACK ANY TABLE TO C##DEBEZIUM;
GRANT SELECT ANY TABLE TO C##DEBEZIUM;


-----------------------------------------------------------------------------------
-- Step 7: Grant SELECT on Each Table (Optional/Extra Security)
GRANT SELECT ON ABFCUBSLIVE.ACZB_HISTORY TO C##DEBEZIUM;
GRANT SELECT ON ABFCUBSLIVE.ACZB_DAILY_LOG TO C##DEBEZIUM;
GRANT SELECT ON ABFCUBSLIVE.STZM_CUST_ACCOUNT TO C##DEBEZIUM;
GRANT SELECT ON ABFCUBSLIVE.STZM_CUSTOMER TO C##DEBEZIUM;
GRANT SELECT ON ABFCUBSLIVE.STZM_TRN_CODE TO C##DEBEZIUM;
GRANT SELECT ON NIPSYSTEM.NIPX_BANKS TO C##DEBEZIUM;
GRANT SELECT ON NIPSYSTEM.NIPX_DIRECT_CREDITS TO C##DEBEZIUM;
GRANT SELECT ON NIPSYSTEM.NIPX_INBOUND_CREDITS TO C##DEBEZIUM;
GRANT SELECT ON WEBSERVE.CSTM_PRODUCT_INTERFACE_MAPPING TO C##DEBEZIUM;
GRANT SELECT ON WEBSERVE.PAYMENT_ROUTER_TXN_LOG TO C##DEBEZIUM;