-- Add Supplemental logs for specific tables to capture all column data for changes to those tables. This is required for Debezium to capture the full change data for those tables.    
-- Run this script after running oracle-preparation-sql-scripts.sql to enable database-level supplemental logging, and before running oracle-table-level-supplemental-log.sql to enable table-level supplemental logging for the tables of interest.

-- Minimal supplemental logging (required — lightweight)
ALTER DATABASE ADD SUPPLEMENTAL LOG DATA;

-- Supplemental logging for primary key columns (required if tables have PKs — lightweight)
ALTER TABLE ABFCUBSLIVE.ACZB_HISTORY           ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
ALTER TABLE ABFCUBSLIVE.ACZB_DAILY_LOG         ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
ALTER TABLE ABFCUBSLIVE.STZM_CUST_ACCOUNT      ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
ALTER TABLE ABFCUBSLIVE.STZM_CUSTOMER          ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
ALTER TABLE ABFCUBSLIVE.STZM_TRN_CODE          ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
ALTER TABLE NIPSYSTEM.NIPX_BANKS               ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
ALTER TABLE NIPSYSTEM.NIPX_DIRECT_CREDITS      ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
ALTER TABLE NIPSYSTEM.NIPX_INBOUND_CREDITS     ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
ALTER TABLE WEBSERVE.CSTM_PRODUCT_INTERFACE_MAPPING ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
ALTER TABLE WEBSERVE.PAYMENT_ROUTER_TXN_LOG    ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;

-- Verify that supplemental logging is enabled at the database level
SELECT SUPPLEMENTAL_LOG_DATA_MIN FROM V$DATABASE;


-- Allow C##CDC to add/remove supplemental logging on any table
GRANT ALTER ANY TABLE TO C##CDC CONTAINER=ALL;


-- Drop supplemental logging on a specific table
ALTER TABLE ABFCUBSLIVE.ACZB_HISTORY DROP SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
ALTER TABLE ABFCUBSLIVE.ACZB_HISTORY DROP SUPPLEMENTAL LOG DATA (PRIMARY KEY) COLUMNS;
ALTER TABLE ABFCUBSLIVE.ACZB_HISTORY DROP SUPPLEMENTAL LOG DATA (UNIQUE) COLUMNS;
ALTER TABLE ABFCUBSLIVE.ACZB_HISTORY DROP SUPPLEMENTAL LOG DATA (FOREIGN KEY) COLUMNS;


-- Drop database-wide supplemental logging (all levels)
ALTER DATABASE DROP SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
ALTER DATABASE DROP SUPPLEMENTAL LOG DATA (PRIMARY KEY) COLUMNS;
ALTER DATABASE DROP SUPPLEMENTAL LOG DATA (UNIQUE) COLUMNS;
ALTER DATABASE DROP SUPPLEMENTAL LOG DATA (FOREIGN KEY) COLUMNS;

-- Drop minimal supplemental logging (do this last — other levels depend on it)
ALTER DATABASE DROP SUPPLEMENTAL LOG DATA;