SET SERVEROUTPUT ON SIZE UNLIMITED
SET FEEDBACK OFF
SET TIMING ON
BEGIN
  GENERATE_CDC_TRANSACTIONS(100000);
  DBMS_OUTPUT.PUT_LINE('Done: 100K records generated');
END;
/
SELECT 'ACZB_HISTORY' AS TBL, COUNT(*) AS CNT FROM ABFCUBSLIVE.ACZB_HISTORY
UNION ALL
SELECT 'NIPX_DIRECT_CREDITS', COUNT(*) FROM NIPSYSTEM.NIPX_DIRECT_CREDITS
UNION ALL
SELECT 'NIPX_INBOUND_CREDITS', COUNT(*) FROM NIPSYSTEM.NIPX_INBOUND_CREDITS
UNION ALL
SELECT 'PAYMENT_ROUTER_TXN_LOG', COUNT(*) FROM WEBSERVE.PAYMENT_ROUTER_TXN_LOG;
EXIT;
